services:
  dev_api:
    build: ./dev_api
    env_file:
      - .env
    depends_on:
      - mongo
  user_api:
    build: ./user_api
    env_file:
      - .env
    depends_on:
      - mongo
  mqtt_con:
    build: ./mqtt_con
    env_file:
      - .env
    depends_on:
      - dev_api
  hw_mock:
    build: ./hw_mock
    env_file:
      - .env
    depends_on:
      - mongo
  line_bot:
    build: ./line_bot
    ports:
      - ${LINE_WEBHOOK_PORT}:${LINE_WEBHOOK_PORT}
    env_file:
      - .env
    depends_on:
      - user_api
  userid_find:
    build: ./userid_find
    env_file:
      - .env
    depends_on:
      - user_api
  heartbeat_cmd_scheduler:
    build: ./heartbeat_cmd_scheduler
    env_file:
      - .env
    depends_on:
      - mongo
      - dev_api
      - mqtt_con
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env

